-- MySQL Script generated by MySQL Workbench
-- Mon Nov  9 15:05:13 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `DNI` INT NOT NULL,
  `num. tarjeta` INT NULL,
  `cod. fidelización` INT NULL,
  PRIMARY KEY (`DNI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleado` (
  `Nombre` VARCHAR(30) NOT NULL,
  `Apellidos` VARCHAR(50) NOT NULL,
  `DNI` INT NOT NULL,
  `Seguridad Social` INT NULL,
  PRIMARY KEY (`DNI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `ID` INT NOT NULL,
  `Fecha` DATE NULL,
  `DNI` INT NOT NULL,
  `Empleado` INT NULL,
  PRIMARY KEY (`ID`, `DNI`),
  INDEX `DNI_idx` (`DNI` ASC) VISIBLE,
  INDEX `Empelado_idx` (`Empleado` ASC) VISIBLE,
  CONSTRAINT `DNI`
    FOREIGN KEY (`DNI`)
    REFERENCES `mydb`.`Cliente` (`DNI`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Empelado`
    FOREIGN KEY (`Empleado`)
    REFERENCES `mydb`.`Empleado` (`DNI`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vivero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vivero` (
  `Código` INT NOT NULL,
  `Ubicación` VARCHAR(45) NULL,
  `Hora apertura` DATETIME NULL,
  `Hora Cierre` DATETIME NULL,
  PRIMARY KEY (`Código`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Zonas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zonas` (
  `Nombre` VARCHAR(50) NOT NULL,
  `Código vivero` INT NOT NULL,
  PRIMARY KEY (`Nombre`, `Código vivero`),
  INDEX `Código vivero_idx` (`Código vivero` ASC) VISIBLE,
  CONSTRAINT `Código vivero`
    FOREIGN KEY (`Código vivero`)
    REFERENCES `mydb`.`Vivero` (`Código`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado_has_Zonas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleado_has_Zonas` (
  `Empleado_DNI` INT NOT NULL,
  `Zonas_Nombre` VARCHAR(50) NOT NULL,
  `Fecha inicio` VARCHAR(45) NULL,
  `Fecha fin` VARCHAR(45) NULL,
  PRIMARY KEY (`Empleado_DNI`, `Zonas_Nombre`),
  INDEX `fk_Empleado_has_Zonas_Zonas1_idx` (`Zonas_Nombre` ASC) VISIBLE,
  INDEX `fk_Empleado_has_Zonas_Empleado1_idx` (`Empleado_DNI` ASC) VISIBLE,
  CONSTRAINT `fk_Empleado_has_Zonas_Empleado1`
    FOREIGN KEY (`Empleado_DNI`)
    REFERENCES `mydb`.`Empleado` (`DNI`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Empleado_has_Zonas_Zonas1`
    FOREIGN KEY (`Zonas_Nombre`)
    REFERENCES `mydb`.`Zonas` (`Nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producto` (
  `Código de barras` INT NOT NULL,
  `Precio` INT NULL,
  `Tipo` VARCHAR(45) NULL,
  `Stock` VARCHAR(45) NULL,
  PRIMARY KEY (`Código de barras`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Zonas_has_Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zonas_has_Producto` (
  `Zonas_Nombre` VARCHAR(50) NOT NULL,
  `Producto_Código de barras` INT NOT NULL,
  PRIMARY KEY (`Zonas_Nombre`, `Producto_Código de barras`),
  INDEX `fk_Zonas_has_Producto_Producto1_idx` (`Producto_Código de barras` ASC) VISIBLE,
  INDEX `fk_Zonas_has_Producto_Zonas1_idx` (`Zonas_Nombre` ASC) VISIBLE,
  CONSTRAINT `fk_Zonas_has_Producto_Zonas1`
    FOREIGN KEY (`Zonas_Nombre`)
    REFERENCES `mydb`.`Zonas` (`Nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Zonas_has_Producto_Producto1`
    FOREIGN KEY (`Producto_Código de barras`)
    REFERENCES `mydb`.`Producto` (`Código de barras`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido_has_Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido_has_Producto` (
  `Pedido_ID` INT NOT NULL,
  `Producto_Código de barras` INT NOT NULL,
  PRIMARY KEY (`Pedido_ID`, `Producto_Código de barras`),
  INDEX `fk_Pedido_has_Producto_Producto1_idx` (`Producto_Código de barras` ASC) VISIBLE,
  INDEX `fk_Pedido_has_Producto_Pedido1_idx` (`Pedido_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_has_Producto_Pedido1`
    FOREIGN KEY (`Pedido_ID`)
    REFERENCES `mydb`.`Pedido` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Pedido_has_Producto_Producto1`
    FOREIGN KEY (`Producto_Código de barras`)
    REFERENCES `mydb`.`Producto` (`Código de barras`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
