-- MySQL Script generated by MySQL Workbench
-- Mon Nov  9 15:01:55 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Zona urbana`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zona urbana` (
  `Nombre` VARCHAR(50) NOT NULL,
  `Area` INT NULL,
  `Población` INT NULL,
  PRIMARY KEY (`Nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Calle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Calle` (
  `Nombre` VARCHAR(50) NOT NULL,
  `Tipo` VARCHAR(45) NULL,
  `Longitud` INT NULL,
  `ZonaUrbana` VARCHAR(45) NULL,
  PRIMARY KEY (`Nombre`),
  INDEX `ZonaUrbana_idx` (`ZonaUrbana` ASC) VISIBLE,
  CONSTRAINT `ZonaUrbana`
    FOREIGN KEY (`ZonaUrbana`)
    REFERENCES `mydb`.`Zona urbana` (`Nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Construccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Construccion` (
  `Numero` INT NOT NULL,
  `Fecha Construccion` DATE NULL,
  `m^2` INT NULL,
  `Calle` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Numero`, `Calle`),
  INDEX `Calle_idx` (`Calle` ASC) VISIBLE,
  CONSTRAINT `Calle`
    FOREIGN KEY (`Calle`)
    REFERENCES `mydb`.`Calle` (`Nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bloque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bloque` (
  `Altura` INT NOT NULL,
  `Aforo` INT NULL,
  `m^2 habitables` INT NULL,
  `construccion` INT NOT NULL,
  PRIMARY KEY (`construccion`),
  CONSTRAINT `construccion`
    FOREIGN KEY (`construccion`)
    REFERENCES `mydb`.`Construccion` (`Numero`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Piso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Piso` (
  `Letra` VARCHAR(1) NOT NULL,
  `Planta` INT NOT NULL,
  `m^2` INT NULL,
  `construccion` INT NOT NULL,
  `Propietario` INT NULL,
  PRIMARY KEY (`Letra`, `Planta`, `construccion`),
  INDEX `construccion_idx` (`construccion` ASC) VISIBLE,
  INDEX `propietario_idx` (`Propietario` ASC) VISIBLE,
  CONSTRAINT `construccion`
    FOREIGN KEY (`construccion`)
    REFERENCES `mydb`.`Bloque` (`construccion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `propietario`
    FOREIGN KEY (`Propietario`)
    REFERENCES `mydb`.`Persona` (`DNI`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Unifamiliar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Unifamiliar` (
  `Habitantes` INT NOT NULL,
  `Numero pisos` VARCHAR(45) NULL,
  `construccion` INT NOT NULL,
  `Propietario` INT NULL,
  PRIMARY KEY (`construccion`),
  INDEX `propietario_idx` (`Propietario` ASC) VISIBLE,
  CONSTRAINT `construccion`
    FOREIGN KEY (`construccion`)
    REFERENCES `mydb`.`Construccion` (`Numero`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `propietario`
    FOREIGN KEY (`Propietario`)
    REFERENCES `mydb`.`Persona` (`DNI`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persona` (
  `Nombre` VARCHAR(50) NOT NULL,
  `DNI` INT NOT NULL,
  `Fecha Nacimiento` DATE NULL,
  `Cabeza Familia` INT NULL,
  `Construcción` INT NULL,
  `LetraBloque` VARCHAR(45) NULL,
  `Planta` INT NULL,
  PRIMARY KEY (`DNI`),
  INDEX `Piso_idx` (`Planta` ASC, `LetraBloque` ASC, `Construcción` ASC) VISIBLE,
  INDEX `Unifamiliar_idx` (`Construcción` ASC) VISIBLE,
  CONSTRAINT `Cabeza Familia`
    FOREIGN KEY (`DNI`)
    REFERENCES `mydb`.`Persona` (`Cabeza Familia`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Piso`
    FOREIGN KEY (`Planta` , `LetraBloque` , `Construcción`)
    REFERENCES `mydb`.`Piso` (`Planta` , `Letra` , `construccion`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `Unifamiliar`
    FOREIGN KEY (`Construcción`)
    REFERENCES `mydb`.`Unifamiliar` (`construccion`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
